### ISSUE TITLE
Move demoman swear list to redis

### ISSUE THREAD

**Issue by Hodgy** [Brunty/dailyshiz-hubot#13]
The swear list should be moved to redis.

This then enables us to add to the list from within slack without needing to modify the code.

Suggestion is for:
* vote system - regular user calls a vote that `x` should be added, shizbot announces the vote and users then have `y` amount of time to vote yes/no.
* admin system - users with the right auth can add remove from the list freely

**Comment by alex-wells** [comment]
sounds good; i'll claim the base part of moving this to redis as it aligns nicely with the auth framework i'm building in as well; the rest of it will need some other genius to work out how to do it :stuck_out_tongue:
